app:
  kafka:
    topics:
      resume-upload: resume.uploads
  open-api:
    description: @project.description@
    title: @project.name@
    version: @project.version@
spring:
  application:
    name: profile-service
  datasource:
    password: ${DATABASE_PASSWORD:password}
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:profile_service}
    username: ${DATABASE_USER:default}
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVERS:localhost:9092}
    properties:
      schema.registry.url: ${SCHEMA_REGISTRY_URL:http://localhost:9090}
    consumer:
      group-id: profile-service-resume-consumer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        specific.avro.reader: true
    producer:
      retries: 10
      acks: all
      properties:
        delivery.timeout.ms: 60000
        request.timeout.ms: 30000
        linger.ms: 0
        max.in.flight.requests.per.connection: 5
        enable.idempotence: true
  profiles:
    active: dev
  flyway:
    enabled: false
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  ai:
    vectorstore:
      pgvector:
        dimensions: 768
    vertex.ai:
      gemini:
        chat:
          options:
            model: ${GEMINI_MODEL:gemini-2.5-flash}
        project-id: ${GCP_PROJECT_ID:}
        location: ${GCP_REGION:us-central1}
        credentials-uri: ${VERTEX_AI_CREDENTIALS_URI:}
      embedding:
        project-id: ${GCP_PROJECT_ID:}
        location: ${GCP_REGION:us-central1}
        credentials-uri: ${VERTEX_AI_CREDENTIALS_URI:}
        text:
          options:
            model: text-embedding-004
eureka:
  instance:
    prefer-ip-address: true
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_PROTOCOL:http}://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
    fetch-registry: true
    register-with-eureka: true
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      probes:
        enabled: true
  health:
    liveness-state:
      enabled: true
    readiness-state:
      enabled: true
jwt:
  secret: ${JWT_SECRET}
  issuer: ${spring.application.name}
  security:
    public-paths: /swagger-ui/**, /v3/api-docs/**, /actuator/health/**, /error/**

---

spring:
  config:
    activate:
      on-profile: confluence
  kafka:
    properties:
      # KAFKA security
      security.protocol: SASL_SSL
      sasl.mechanism: PLAIN
      sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username='${KAFKA_API_KEY:}' password='${KAFKA_API_SECRET:}';
      basic.auth.credentials.source: USER_INFO
      # schema registry api key
      schema.registry.basic.auth.user.info: ${SCHEMA_REGISTRY_API_KEY:}:${SCHEMA_REGISTRY_API_SECRET:}
